export const lightTypes = {
    CHANGE_POSITION: 'CHANGE_POSITION',
    CHANGE_AMBIENT_LIGHT: 'CHANGE_AMBIENT_LIGHT',
    CHANGE_DIFFUSE_LIGHT: 'CHANGE_DIFFUSE_LIGHT',
    CHANGE_SPECULAR_LIGHT: 'CHANGE_SPECULAR_LIGHT',
};
